# Generated by Django 2.1.2 on 2018-11-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181122_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
