# Generated by Django 2.1.2 on 2018-11-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp_gallery', '0002_auto_20181121_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='shop_project/media/'),
        ),
    ]
