# Generated by Django 2.1.2 on 2018-11-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp_gallery', '0003_auto_20181121_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='subapp_gallery/static/media'),
        ),
    ]
